POST http://localhost:3000/api/plans
Content-Type: application/json


{
    "name": "professionalPlus",
    "price": 199.99
}
###

GET http://localhost:3000/api/plans

###

GET http://localhost:3000/api/plans/2

###

PUT http://localhost:3000/api/plans/1
Content-Type: application/json

{
    "name": "basic",
    "price": 19.99
}

###
DELETE http://localhost:3000/api/plans/1


###